trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- checkout: self
  submodules: recursive

- script: |
    set -e
    # cd / IS REQUIRED! If you don't do it pip fails, presumably
    # because of something in the mypaint repository confuses it
    # because Python developers don't understand how to write
    # robust software.
    cd /
    python3 -m pip install --upgrade pip setuptools wheel
    brew install autoconf automake intltool gobject-introspection libffi json-c libtool gettext gtk+3 numpy pygobject3 little-cms2 swig adwaita-icon-theme
    pip3 install pyinstaller
  displayName: 'Install requirements'

- script: |
    set -e
    mkdir install
  displayName: 'Create install dir'

- script: |
    set -e
    # gettext is required even though we disable i18n.
    brew link --force gettext
    cd libmypaint
    ./autogen.sh
    # i18n is disabled because it depends on some perl XML parser (yes
    # really, in 2019) and I cannot get it to install properly.
    ./configure --prefix=`pwd`/../install --disable-i18n
    make -j4
    make check
    make install
    brew unlink gettext
  displayName: 'Build libmypaint'

- script: |
    set -e
    cd mypaint-brushes
    ./autogen.sh
    # We must use backticks because dollar-brackets are used for
    # Azure Pipelines variables and there's no documentation on
    # how to escape them.
    ./configure --prefix=`pwd`/../install
    make install
  displayName: 'Build mypaint-brushes'

- script: |
    set -e
    cd mypaint
    export PKG_CONFIG_PATH=../install/lib/pkgconfig/:../install/share/pkgconfig
    export CFLAGS="-D_DARWIN_C_SOURCE"
    # Required, even though we disabled i18n.
    brew link --force gettext
    python3 setup.py build_config --brushdir-path='{installation-prefix}/MacOS/share/mypaint-data/2.0/brushes' build
    brew unlink gettext
  displayName: 'Build mypaint'

- script: |
    set -e
    cd mypaint
    pyinstaller mypaint.spec --windowed
    # Remove these huge X11 cursors that don't seem to be used. I suspect
    # there is a way to do this from mypaint.spec but I can't work out how.
    rm -rf dist/MyPaint.app/Contents/MacOS/share/icons/Adwaita/cursors
    # Remove non-app bundle files.
    rm -rf dist/mypaint
  displayName: 'Making application installer'

- script: |
    set -e
    hdiutil create -volname MyPaint -srcfolder mypaint/dist -ov -format UDZO $(Build.ArtifactStagingDirectory)/MyPaint.dmg
  displayName: 'Make DMG'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop
