trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- checkout: self
  submodules: recursive
  persistCredentials: true

- script: |
    set -e
    # cd / IS REQUIRED! If you don't do it pip fails, presumably
    # because of something in the mypaint repository confuses it
    # because Python developers don't understand how to write
    # robust software. Although actually I ended up using brew instead
    # of pip I've left this just in case.
    cd /
    python3 -m pip install --upgrade pip setuptools wheel
    brew install autoconf automake intltool gobject-introspection libffi json-c libtool gettext gtk+3 numpy pygobject3 little-cms2 swig
  displayName: 'Install requirements'

- script: |
    set -e
    mkdir install
  displayName: 'Create install dir'

- script: |
    set -e
    # gettext is required even though we disable i18n.
    brew link --force gettext
    cd libmypaint
    ./autogen.sh
    # i18n is disabled because it depends on some perl XML parser (yes
    # really, in 2019) and I cannot get it to install properly.
    ./configure --prefix=`pwd`/../install --disable-i18n
    make -j4
    make check
    make install
    brew unlink gettext
  displayName: 'Build libmypaint'

- script: |
    set -e
    cd mypaint-brushes
    ./autogen.sh
    # We must use backticks because dollar-brackets are used for
    # Azure Pipelines variables and there's no documentation on
    # how to escape them.
    ./configure --prefix=`pwd`/../install
    make install
  displayName: 'Build mypaint-brushes'

- script: |
    set -e
    cd mypaint
    export PKG_CONFIG_PATH=../install/lib/pkgconfig/:../install/share/pkgconfig
    export CFLAGS="-D_DARWIN_C_SOURCE"
    # Required, even though we disabled i18n.
    brew link --force gettext
    python3 setup.py build
    brew unlink gettext
  displayName: 'Build mypaint'

- script: |
    set -e
    cd mypaint
    python3 setup.py install
  displayName: 'Install mypaint'
